# Generated by Django 3.2.6 on 2021-08-26 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triplaner', '0002_auto_20210826_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
