# Generated by Django 3.2.6 on 2021-08-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplaner', '0004_destination_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='slug',
        ),
    ]
